name: deploy
on: [ push ]
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/web/kaden.sh/build/
      - name: run server via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: node /home/web/kaden.sh/build/index.js
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ""
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}