name: deploy
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/web/kaden.sh/build
            git pull
            npm run build
            node index.js